### ISSUE TITLE
Pytorch3D version

### ISSUE THREAD

**Issue by feandalo** [WangLongZJU/DeepAC#1]
Hello!

Thanks for making the code available! :)

It seems PyTorch3D 0.7.1 does not support PyTorch 1.8.
From https://github.com/facebookresearch/pytorch3d/releases/tag/v0.7.1: "PyTorch 1.8 is no longer supported. We support from PyTorch 1.9.0 to PyTorch 1.12.1."

Is it possible to run your code with a different PyTorch or PyTorch3D version?

Thanks!

**Comment by Jianxff** [comment]
I have test it with python3.9. The following versions are tested good on my device:
pytorch==1.11.0 
torchvision==0.12.0
torchaudio==0.11.0`
pytorch3d==0.7.1`
pytorch-lightning==1.8.1

**Comment by WangLongZJU** [comment]
> Hello!
> 
> Thanks for making the code available! :)
> 
> It seems PyTorch3D 0.7.1 does not support PyTorch 1.8. From https://github.com/facebookresearch/pytorch3d/releases/tag/v0.7.1: "PyTorch 1.8 is no longer supported. We support from PyTorch 1.9.0 to PyTorch 1.12.1."
> 
> Is it possible to run your code with a different PyTorch or PyTorch3D version?
> 
> Thanks!

In the official document of Pytorch3D,  v0.7.1 does not support pytorch 1.8.
But, I test the Installation on my computer. It can work.

**Comment by WangLongZJU** [comment]
> I have test it with python3.9. The following versions are tested good on my device:
> 
> ```
> pytorch==1.11.0 
> torchvision==0.12.0
> torchaudio==0.11.0
> pytorch3d==0.7.1
> pytorch-lightning==1.8.1
> ```

Thanks for your test.

**Comment by Jianxff** [comment]
> > I have test it with python3.9. The following versions are tested good on my device:
> > ```
> > pytorch==1.11.0 
> > torchvision==0.12.0
> > torchaudio==0.11.0
> > pytorch3d==0.7.1
> > pytorch-lightning==1.8.1
> > ```
> 
> Thanks, @Jianxff . Which CUDA version are you using?

@feandalo , I'm using cuda 11.5
