### ISSUE TITLE
Where can I find supplementary material?

### ISSUE THREAD

**Issue by sp9103** [WangLongZJU/DeepAC#18]
Hi, 
Thank you for sharing your research.

I would like to know the formulation for statistical foreground probability and statistical boundary probability, but the paper says to refer to the supplementary material. Where can I find the supplementary material?

**Comment by WangLongZJU** [comment]
https://zju3dv.github.io/deep_ac/videos/DeepAC_sup.pdf

**Comment by sp9103** [comment]
Thank you for responding quickly.
