### ISSUE TITLE
About output pose in demo

### ISSUE THREAD

**Issue by Jianxff** [WangLongZJU/DeepAC#2]
Greate work. Thanks for opening source!

In the demo I found that the output video has been into square shape. In this case, the 6DoF pose of the object is not suite for the original image (is that right?). How to render the pose on the original image which has not been cropped ? Just as the video shown in the project page. 
![image](https://github.com/WangLongZJU/DeepAC/assets/35654252/e42a1751-7f61-432d-aa04-ddc104e0246c)

Another question, I found in `model._forward` which gets the prediction, the data does not need bbox info, so if it is possible to run inference without 2d bbox information?
![image](https://github.com/WangLongZJU/DeepAC/assets/35654252/8341c48e-8810-456d-82bf-b3d252d5a775)

Thanks.

**Comment by WangLongZJU** [comment]
> Greate work. Thanks for opening source!
> 
> In the demo I found that the output video has been into square shape. In this case, the 6DoF pose of the object is not suite for the original image (is that right?). How to render the pose on the original image which has not been cropped ? Just as the video shown in the project page. ![image](https://private-user-images.githubusercontent.com/35654252/298541895-e42a1751-7f61-432d-aa04-ddc104e0246c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTk0NjIsIm5iZiI6MTcwNTkxOTE2MiwicGF0aCI6Ii8zNTY1NDI1Mi8yOTg1NDE4OTUtZTQyYTE3NTEtN2Y2MS00MzJkLWFhMDQtZGRjMTA0ZTAyNDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDEwMjYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMWJkZGNiODkwMWVhYWEzZDc3ZmNiYzMyYTkxMzU3NzFiZmRiOWIzNTY3N2Q4YThlODE2MmU0YjRjYjNlYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qN2oda4G3r40quPKGX1rvBYzq7DnMpXtEIWpSz34Jqk)
> 
> Another question, I found in `model._forward` which gets the prediction, the data does not need bbox info, so if it is possible to run inference without 2d bbox information? ![image](https://private-user-images.githubusercontent.com/35654252/298541998-8341c48e-8810-456d-82bf-b3d252d5a775.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTk0NjIsIm5iZiI6MTcwNTkxOTE2MiwicGF0aCI6Ii8zNTY1NDI1Mi8yOTg1NDE5OTgtODM0MWM0OGUtODgxMC00NTZkLTgyYmYtYjNkMjUyZDVhNzc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDEwMjYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNzkzZDcyMTE4MDhlMGExNmIyOWMzYjIzMzQ5NWE0OTIxNzE5YWJhODc0ZTY3ZGM3MTUyZjgwZWQ4MDIzMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zajeqHE7eJQo8W9BWeO3ZueCfL2SbuwV5nZjguMp5sM)
> 
> Thanks.

1.  The original image will be cropped because DeepAc needs to focus on the surrounding region of the object.
2. The cropped image will be resized and padded to the input size that we use to train the network.
3. The operations of crop, resize, and pad just update the camera's intrinsic parameters. They do not update the object pose.
4. If you want to output the video for the original image size, you can save the poses 'pred['opt_body2view_pose'][-1][0]'.
5. Via the pose and camera of each original image, you can render whatever you want.

**Comment by Jianxff** [comment]
> > Greate work. Thanks for opening source!
> > In the demo I found that the output video has been into square shape. In this case, the 6DoF pose of the object is not suite for the original image (is that right?). How to render the pose on the original image which has not been cropped ? Just as the video shown in the project page. ![image](https://private-user-images.githubusercontent.com/35654252/298541895-e42a1751-7f61-432d-aa04-ddc104e0246c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTk0NjIsIm5iZiI6MTcwNTkxOTE2MiwicGF0aCI6Ii8zNTY1NDI1Mi8yOTg1NDE4OTUtZTQyYTE3NTEtN2Y2MS00MzJkLWFhMDQtZGRjMTA0ZTAyNDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDEwMjYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMWJkZGNiODkwMWVhYWEzZDc3ZmNiYzMyYTkxMzU3NzFiZmRiOWIzNTY3N2Q4YThlODE2MmU0YjRjYjNlYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qN2oda4G3r40quPKGX1rvBYzq7DnMpXtEIWpSz34Jqk)
> > Another question, I found in `model._forward` which gets the prediction, the data does not need bbox info, so if it is possible to run inference without 2d bbox information? ![image](https://private-user-images.githubusercontent.com/35654252/298541998-8341c48e-8810-456d-82bf-b3d252d5a775.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTk0NjIsIm5iZiI6MTcwNTkxOTE2MiwicGF0aCI6Ii8zNTY1NDI1Mi8yOTg1NDE5OTgtODM0MWM0OGUtODgxMC00NTZkLTgyYmYtYjNkMjUyZDVhNzc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDEwMjYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNzkzZDcyMTE4MDhlMGExNmIyOWMzYjIzMzQ5NWE0OTIxNzE5YWJhODc0ZTY3ZGM3MTUyZjgwZWQ4MDIzMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zajeqHE7eJQo8W9BWeO3ZueCfL2SbuwV5nZjguMp5sM)
> > Thanks.
> 
> 1. The original image will be cropped because DeepAc needs to focus on the surrounding region of the object.
> 2. The cropped image will be resized and padded to the input size that we use to train the network.
> 3. The operations of crop, resize, and pad just update the camera's intrinsic parameters. They do not update the object pose.
> 4. If you want to output the video for the original image size, you can save the poses 'pred['opt_body2view_pose'][-1][0]'.
> 5. Via the pose and camera of each original image, you can render whatever you want.

Thanks so much for your reply! I will try it later.
