### ISSUE TITLE
prerender parameters

### ISSUE THREAD

**Issue by feandalo** [WangLongZJU/DeepAC#3]
Hello!

I would like to run inference on my own data and I was trying to understand all parameters in MyModel.yaml.

Do I need to change sphere_radius and maximum_body_diameter according to my own model?
If yes, what do these parameters mean?

Thank you!

**Comment by WangLongZJU** [comment]
1. maximum_body_diameter means the radius of your object. 
2. sphere_radius is the distance between cameras and your object. DeepAC samples several cameras from a sphere and the radius of the sphere is sphere_radius.
3. For example, the diameter of your object is 0.1m, the maximum_body_diameter should be bigger than 0.1m, such as 0.3, 0.5 and 0.8. Besides, the sphere_radius should be bigger than the maximum_body_diameter, such as 0.8, 1.0 and 1.2.
4. Set the output_mask to True in your config. The rendered masks will be automatically saved. Make sure that you can watch the whole mask of your object from a sampled camera. If not , you need to update the maximum_body_diameter and sphere_radius to a bigger value.
