### ISSUE TITLE
pose.txt

### ISSUE THREAD

**Issue by Wahaha-code** [WangLongZJU/DeepAC#4]
When I was reasoning about my own data, I did not have a pose.txt. I would like to ask what this is and how I can generate it.

**Comment by WangLongZJU** [comment]
1. DeepAC needs the init pose of the first frame for tracking. Estimating the pose via a single image is not the task of DeepAC.
2. If you test DeepAC on a public dataset, you just provide the pose of first frame in the pose.txt. You can find how DeepAC uses the pose.txt in demo.py.
3. Otherwise, you need to use other pose estimation method to get the pose of the first frame.

**Comment by Wahaha-code** [comment]
Thank you for your reply. At the same time, I would like to ask. This pose.txt does not seem to be a simple rotation offset matrix. Can you explain what it means?Thanks again.

**Comment by WangLongZJU** [comment]
> Thank you for your reply. At the same time, I would like to ask. This pose.txt does not seem to be a simple rotation offset matrix. Can you explain what it means?Thanks again.

1. Each line of the pose.txt corresponds to the gt_pose of your images.
2. Each line has 12 parameters. The parameters[:9] is the rotation matrix(will be reshaped to a 3x3 matrix) and parameters[9:] is the translation of the pose.

**Comment by Wahaha-code** [comment]
Does that mean that I have to give the real pose of the first 200 frames during inference?

One more question is how can I visualize the grid pkl file.

thanks again

**Comment by WangLongZJU** [comment]
> Does that mean that I have to give the real pose of the first 200 frames during inference?
> 
> One more question is how can I visualize the grid pkl file.
> 
> thanks again

1. You just provide the real pose of the first frame, not the first 200 frames during inference.
2. If you want to know more information about the pkl file, I suggest you to read the detailed implement of the prerender.py.
