### ISSUE TITLE
About Prediction Scoring

### ISSUE THREAD

**Issue by Jianxff** [WangLongZJU/DeepAC#7]
Thanks the good work!
I am interested in the scoring method for 6d pose prediction.
Can DeepAC know the predicted pose is good or not ?
Just like the demo video (iOS) on the project page, how does the program know when to start tracking from initialization?

**Comment by WangLongZJU** [comment]
If the predicted pose is good, the mean of each correspondence line will be located in the middle of this line, and the variance will be small. 
We can use these means and variances to compute a probability that represents the predicted pose of whether it is good or not.

**Comment by Jianxff** [comment]
Thank you so much !
